services:
  nats:
    restart: always
  postgres:
    restart: always
  postgate:
    restart: always
  openworkers-runner:
    restart: always
  openworkers-logs:
    restart: always
  openworkers-scheduler:
    restart: always
  openworkers-proxy:
    restart: always
    ports:
      - 5080:80
      - 50443:443
    entrypoint:
      [
        "/usr/sbin/nginx",
        "-c",
        "/etc/nginx/nginx.prod.conf",
        "-g",
        "daemon off;",
      ]
