upstream postgate_server {
  server postgate:6080;
  keepalive 16;
}

server {
  http2 on;
  listen 443 ssl;
  server_name postgate.dev.kube postgate.dev.localhost postgate.openworkers.dev postgate.openworkers.com;

  set $sid 'postgate';

  # SSL configuration
  include rules/ssl.conf;

  # Proxy to Postgate
  location / {
    add_header X-Matching-Path  postgate   always;
    add_header X-Request-Id     $rid       always;
    add_header X-Server-Id      $sid       always;
    add_header X-Proxy-Name     $hostname  always;

    client_max_body_size 10M;

    include rules/proxy.conf;
    proxy_pass http://postgate_server;
  }
}
